FORMAT: 1A
HOST: https://api.inudevs.com

# INU Server Docs
<div style="text-align:center">
<img src="./profile.png" width="150px">
</div>

## INU?
INU는 `모두가 마음대로 꿈을 펼칠 수 있는 세상`을 만들고자 하는 동아리입니다.

<br/>
<br/>

# Group INU API Gateway

## 개발 배경
처음에 저희는 INU에서 새로운 프로젝트를 진행할 때마다 백엔드를 처음부터 하나하나 다시 개발하고 배포했습니다.
그랬기 때문에 각 서비스마다 데이터베이스와 계정이 따로 존재해야만 했죠.

하지만 머지않아 공통된 인증과 데이터베이스가 필요해지기 시작했습니다.
그렇다고 하나의 서버에 모든 서비스를 돌리자면 앞으로 진행하는 모든 프로젝트의 백엔드를 하나의 프레임워크로 개발해야 하게 되고,
새로운 트렌드나 기술을 적용하거나 유지보수하기 까다로워집니다.
그래서 선택한 것이 바로 **마이크로서비스 아키텍처** 입니다.

각각의 서비스들을 독립적으로 배포하면서도 커다란 사용자 데이터베이스와 인증 방식을 공유하고,
하나의 API로 제공하기 위한 **API 게이트웨이** 를 두는 것입니다.

즉, 모든 INU의 서비스가 하나의 계정에 제공되므로 서비스 간 이동에서 로그인을 되풀이할 필요가 없고,
보다 쉽게 전체 서비스와 데이터를 모니터링하고 관리할 수 있습니다.

해커톤이나 공모전 등을 위한 프로젝트를 진행할 때도 본 API를 이용하면 사용자 모델이나 인증 따위에 시간을 낭비할 필요 없이 바로 서비스에 집중할 수 있습니다.

## Group 예시

## Test [/test]
테스트

### 테스트 [GET]
도큐먼테이션 예시를 보여주기 위한 테스트 엔드포인트입니다.

+ Response 200 (application/json)

    + Body

            {
                "test": true
            }

## Group 사용자 인증
<!-- include(./auth.apib) -->

## Group 서비스 관리
<!-- include(./service.apib) -->

## Group 사용자
<!-- include(./user.apib) -->
