## 로그 [/log]
로그를 다룹니다.

### 로그 모델

```js
{
    "id" : "5d835eabf8da0887183f37a4",
    "path" : "/",
    "method" : "GET",
    "status" : 304,
    "elapsed" : 7.697316,
    "timestamp" : 1568890539330
}
```

## 최근 로그 [GET]
