## 로그 [/log]
로그를 다룹니다.

### 로그 모델

```js
{
    "id" : "5d835eabf8da0887183f37a4",
    "path" : "/",
    "method" : "GET",
    "status" : 304,
    "elapsed" : 7.697316,
    "timestamp" : 1568890539330
}
```

## 최근 로그 [GET]

+ Response 200 (application/json)

    + Body

            {
                "start": 1568806046247,
                "end": 1568892446247,
                "logs": [
                    {
                        "path": "/",
                        "method": "POST",
                        "status": 200,
                        "elapsed": 164.302734,
                        "timestamp": 1568890491692,
                        "id": "5d835e7bf8da0887183f37a1"
                    },
                    ...
                ]
            }
