## Dashboard [/user]
액세스 토큰의 사용자 정보를 제공합니다.

### 개인 대시보드 [GET]

## User [/user/{userID}]
특정 사용자에 대한 정보를 제공합니다.

+ Parameters
    + userID: `5d79e66575a8030b5ec6c119` (required, string) - 사용자 ID

### 사용자 정보 [GET]
